"""voter table

Revision ID: 0dbe1f25aef3
Revises: 
Create Date: 2018-12-01 14:20:04.363584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbe1f25aef3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voter_email'), 'voter', ['email'], unique=True)
    op.create_index(op.f('ix_voter_name'), 'voter', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voter_name'), table_name='voter')
    op.drop_index(op.f('ix_voter_email'), table_name='voter')
    op.drop_table('voter')
    # ### end Alembic commands ###
